### ISSUE TITLE
Why your accuracy of teacher hourglass is so high?(90.5 on val)

### ISSUE THREAD

**Issue by sumaliqinghua** [ilovepose/fast-human-pose-estimation.pytorch#4]
Dear authors,
thx for your nice works. I have a doubt about the teacher model.
Isn't 89.2 on MPII validation? Is it the original hourglass? or you modified it? thx for your reply.

**Comment by HuAndrew** [comment]
Hi, 90.5 model is PyTorch hourglass, the original hourglass is released by lua.

In fact, 8 hourglass best performance is similar to HRNet 32 results.
