### ISSUE TITLE
Training HRNet-w32 student model from scratch

### ISSUE THREAD

**Issue by jin-s13** [ilovepose/fast-human-pose-estimation.pytorch#6]
Thank you for releasing the code. 
I am trying to reproduce the result (training HRNet w32 student network on MSCOCO dataset). 
It seems that the student network is already pretrained on MSCOCO with 74.4 mAP. 

I wonder if the student network can be trained from scratch with FPD setting (pretrained on imagenet / rather than pre-trained on MSCOCO). 

Have you tried training the student network from scratch?

**Comment by jin-s13** [comment]
In the MPII experiment, it seems that training from scratch using FPD training scheme (hourglass_student_FPD*) performs worse than directly training with gt (hourglass_student).

The comparison between 'hourglass_student_FPD' vs 'hourglass_student', seems a little bit unfair. Since hourglass_student_FPD is trained with more (double) epochs.

**Comment by xizero00** [comment]
Good question! 
>>The comparison between 'hourglass_student_FPD' vs 'hourglass_student', seems a little bit unfair. Since hourglass_student_FPD is trained with more (double) epochs.

If you train the same model without FPD from scratch(or pretrained on coco) for the double number of epochs, you will find the model trained from scratch(or pretrained on coco) still can not catch up with the FPD's student model. 
In fact, we have already noticed the saturation problem.
The model without FPD trained from scratch(or pretrained on coco) has already saturated.
Extending the number of epochs doesn't help improve the performance of the model.
However, FPD is able to provide extra information(see Fig.3 in our paper) which can boost the model's performance.

**Comment by xizero00** [comment]
>>The reason why hourglass_student_FPD* cannot catch up with hourglass_student_FPD

I try to provide an explanation:
The knowledge from the teacher model is not always correct.
If we trained the student model from scratch using FPD, this may hurt the student model's low-level feature representation preventing learning a good feature extractor.
