### ISSUE TITLE
cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/color.cpp:11115: error: (-215) scn == 3 || scn == 4 in function cvtColor

### ISSUE THREAD

**Issue by genius9527** [ilovepose/fast-human-pose-estimation.pytorch#9]
Hi, when I trained with your code, I encountered the following problem：
cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/color.cpp:11115: error: (-215) scn == 3 || scn == 4 in function cvtColor

**Comment by xizero00** [comment]
@genius9527 
Hi, 
Do you have gray image(one channel) in your dataset?
Please check the image and make sure the image have 3 or 4 channels.
